CREATE TABLE Organizador (
    Nome VARCHAR(100) PRIMARY KEY
);

CREATE TABLE Integrante (
    CPF VARCHAR(14) PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Nick VARCHAR(50) NOT NULL,
    Situacao VARCHAR(20)
);

CREATE TABLE Tecnico (
    CPF VARCHAR(14) PRIMARY KEY,
    FOREIGN KEY (CPF) REFERENCES Integrante(CPF)
);

CREATE TABLE Jogador (
    CPF VARCHAR(14) PRIMARY KEY,
    Funcao VARCHAR(50),
    FOREIGN KEY (CPF) REFERENCES Integrante(CPF)
);